### PR TITLE
Fix EM6 errors and enable plugin for 3.23.90 and 3.24

### PR DESCRIPTION
**Pull request by miigotu**
Replaces #16 

This fixes the errors that make the plugin not work on gnome-shell 3.23.90-3.24

### CODE REVIEW

**Comment by Tomsgu** [comment]
Thanks for the PR. It works very well on my machine. gnome-3.24.1 Hope it will be merged soon.

**Comment by miigotu** [comment]
NP, I have been using these changes for 7.5 months, no problems so far.

**Comment by miigotu** [comment]
Thanks

**Comment by optimisme** [comment]
Sorry for the delay.

**Comment by miigotu** [comment]
Not a problem, everyone is busy =P

**Pull request merged**
